=== tristrambrelstaff/Ichneumonidae-keys/key.dtd
<!ELEMENT key (title, note*, (singlet+ | couplet+))>
<!ATTLIST key
  ref     CDATA #REQUIRED
  doc_ref CDATA #REQUIRED
  lang    CDATA "en"
>

<!ELEMENT title (#PCDATA)>

<!ELEMENT note (#PCDATA)>

<!ELEMENT singlet (((property+ | set), (taxon+ | set)?), note*)>
<!ATTLIST singlet
  ref      CDATA #REQUIRED
  else_ref CDATA #REQUIRED
>

<!ELEMENT couplet (lead, lead+)>
<!ATTLIST couplet
  ref      CDATA #REQUIRED
  else_ref CDATA ""
>

<!ELEMENT lead (((property+ | set), (taxon+ | set)?), note*)>
<!ATTLIST lead
  then_ref CDATA ""
>

<!ELEMENT property (#PCDATA)>

<!ELEMENT taxon (#PCDATA)>

<!ENTITY % set_types "property | taxon">

<!ELEMENT set (%set_types; | and | or | not)>
<!-- Must only contain members of one set_type -->

<!ELEMENT and ((%set_types; | set)*)>
<!-- Must only contain members of the same set_type as the enclosing set -->

<!ELEMENT or ((%set_types; | set)*)>
<!-- Must only contain members of the same set_type as the enclosing set -->

<!ELEMENT not (%set_types; | set)>
<!-- Must only contain elements of the same set_type as the enclosing set -->

=== tristrambrelstaff/Ichneumonidae-keys/doc/Hilpert-1992/key/Ichneumon-females-A1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE key SYSTEM "../key.dtd">

<key ref="Ichneumon-females-A1" doc_ref="Hilpert-1992" lang="de">

  <title>Gruppe A1</title>

  <singlet ref="1" else_ref="4">
    <property>
      Große Arten (13,2-15,5)
    </property>
  </singlet>

  <singlet ref="2" else_ref="3">
    <property>
      TiIII apikal zu 1/4 schwarz.
    </property>
    <taxon>
      I. xanthorius FORSTER
    </taxon>
  </singlet>

  <singlet ref="3" else_ref="2">
    <property>
      TiIII apikal nicht schwarz, nur wenig rot
    </property>
    <taxon>
      I. sexcinctus GRAVENHORST
    </taxon>
  </singlet>

  <singlet ref="4" else_ref="1">
    <property>
      Kleinere Art (bis 11,6).
    </property>
    <property>
      (Scutellum oft nicht ganz weiß, weißer Fleck nur nierenförmig.)
    </property>
    <taxon>
      I. ostentator HEINRICH
    </taxon>
  </singlet>

</key>
